//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chord
    {
        public Chord()
        {
            this.Intervals = new HashSet<Interval>();
        }
    
        public int Id { get; set; }
        public int ProgressionId { get; set; }
    
        public virtual ICollection<Interval> Intervals { get; set; }
        public virtual Progression Progression { get; set; }
    }
}
