//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public IDbSet<Guitar> Guitars { get; set; }
        public IDbSet<Neck> Necks { get; set; }
        public IDbSet<String> Strings { get; set; }
        public IDbSet<Fret> Frets { get; set; }
        public IDbSet<Note> Notes { get; set; }
        public IDbSet<Octave> Octaves { get; set; }
        public IDbSet<Scale> Scales { get; set; }
        public IDbSet<Chord> Chords { get; set; }
        public IDbSet<Degree> Degrees { get; set; }
        public IDbSet<Progression> Progressions { get; set; }
        public IDbSet<Mode> Modes { get; set; }
        public IDbSet<ParallelMode> ParallelModes { get; set; }
        public IDbSet<DerivativeMode> DerivativeModes { get; set; }
        public IDbSet<Interval> Intervals { get; set; }
        public IDbSet<Key> Keys { get; set; }
        public IDbSet<Tuning> Tunings { get; set; }
    }
}
