//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Guitar> Guitars { get; set; }
        public DbSet<Neck> Necks { get; set; }
        public DbSet<String> Strings { get; set; }
        public DbSet<Fret> Frets { get; set; }
        public DbSet<Note> Notes { get; set; }
        public DbSet<Octave> Octaves { get; set; }
        public DbSet<Scale> Scales { get; set; }
        public DbSet<Chord> Chords { get; set; }
        public DbSet<Degree> Degrees { get; set; }
        public DbSet<Progression> Progressions { get; set; }
        public DbSet<Mode> Modes { get; set; }
        public DbSet<ParallelMode> ParallelModes { get; set; }
        public DbSet<DerivativeMode> DerivativeModes { get; set; }
        public DbSet<Interval> Intervals { get; set; }
        public DbSet<Key> Keys { get; set; }
        public DbSet<Tuning> Tunings { get; set; }
    }
}
