//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neck
    {
        public Neck()
        {
            this.Strings = new HashSet<String>();
            this.Frets = new HashSet<Fret>();
        }
    
        public int Id { get; set; }
        public int GuitarId { get; set; }
    
        public virtual Guitar Guitar { get; set; }
        public virtual ICollection<String> Strings { get; set; }
        public virtual ICollection<Fret> Frets { get; set; }
        public virtual Tuning Tuning { get; set; }
    }
}
