//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progression
    {
        public Progression()
        {
            this.Chords = new HashSet<Chord>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Chord> Chords { get; set; }
    }
}
