//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scale
    {
        public Scale()
        {
            this.Intervals = new HashSet<Interval>();
            this.Modes = new HashSet<Mode>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Interval> Intervals { get; set; }
        public virtual ICollection<Mode> Modes { get; set; }
        public virtual Key Key { get; set; }
    }
}
