//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class String
    {
        public int Id { get; set; }
        public int NeckId { get; set; }
        public int NoteId { get; set; }
    
        public virtual Neck Neck { get; set; }
        public virtual Note OpenNote { get; set; }
    }
}
